#.github/workflowsディレクトリ配下にymlファイルは複数配置できる。
name: Manual(wokflows_name)_input_parameter 
on: 
  workflow_dispatch: #手動実行用のonキー。
    inputs: #ユーザーが入力するパラメータを定義する。
      input_parameter_name1: #パラメータ名
        description: 'パラメータの説明。[挨拶の言葉]を入力。' #パラメータの説明
        required: true #必須かどうか
        default: 'Hello' #デフォルト値
      input_parameter_name2: #パラメータ名
        description: 'パラメータの説明。[挨拶する相手]を入力。' #パラメータの説明
        required: true #必須かどうか
        default: 'world' #デフォルト値

jobs: 
  manual2_jobID: 
    #name: hello_name 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "${{ inputs.input_parameter_name1 }}, ${{ inputs.input_parameter_name2 }}. yml2. job1" 
      - uses: actions/checkout@v4 
